import os, json, random, subprocess, time
from datetime import datetime
import requests

DATA = "/data"
CONFIG_PATH = "/app/config.json"

def load_config():
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        return json.load(f)

def ollama_generate(prompt: str, model: str, url: str):
    payload = {"model": model, "prompt": prompt, "stream": False}
    r = requests.post(url, json=payload, timeout=600)
    r.raise_for_status()
    return r.json().get("response", "").strip()

def pick_topic(topic_file: str):
    with open(topic_file, "r", encoding="utf-8") as f:
        lines = [x.strip() for x in f.readlines() if x.strip()]
    if not lines:
        raise RuntimeError(f"No topics found in {topic_file}")
    return random.choice(lines)

def ensure_dir(p): os.makedirs(p, exist_ok=True)

def run(cmd):
    # cmd list
    p = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    if p.returncode != 0:
        raise RuntimeError("CMD FAILED:\n" + " ".join(cmd) + "\n\n" + p.stdout)
    return p.stdout

def write_text(path, text):
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)

def read_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

def write_json(path, obj):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2)

def piper_tts(piper_exe, voice_model, text_path, out_wav):
    # Piper CLI usage varies by build; adjust if your piper exe differs.
    # Common pattern:
    # piper.exe --model <model.onnx> --output_file out.wav < input.txt
    with open(text_path, "r", encoding="utf-8") as f:
        text = f.read()
    p = subprocess.Popen(
        [piper_exe, "--model", voice_model, "--output_file", out_wav],
        stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True
    )
    out, _ = p.communicate(text)
    if p.returncode != 0:
        raise RuntimeError("PIPER FAILED:\n" + out)

def build_video_ffmpeg(audio_wav, out_mp4, title, lang):
    """
    Simple safe video:
    - solid background + big captions (burned)
    - no copyrighted music
    - uses subtitles (.srt) generated by simple timing
    """
    # Create a simple SRT with rough timing (better: whisper align later)
    # Here we do minimal: one caption = title for 8 seconds
    srt_path = out_mp4.replace(".mp4", ".srt")
    srt = "1\n00:00:00,000 --> 00:00:08,000\n" + title + "\n"
    write_text(srt_path, srt)

    # Background + audio + subtitles burned
    # 1280x720, 30fps
    font = "Arial"
    vf = f"subtitles='{srt_path}':force_style='FontName={font},FontSize=42,PrimaryColour=&H00FFFFFF&,OutlineColour=&H00000000&,BorderStyle=3,Outline=2'"

    cmd = [
        "ffmpeg", "-y",
        "-f", "lavfi", "-i", "color=c=black:s=1280x720:r=30",
        "-i", audio_wav,
        "-vf", vf,
        "-shortest",
        "-c:v", "libx264", "-pix_fmt", "yuv420p",
        "-c:a", "aac", "-b:a", "192k",
        out_mp4
    ]
    run(cmd)

def main():
    cfg = load_config()

    channel = os.environ.get("CHANNEL", "EN").upper().strip()  # EN or TE
    if channel not in ("EN", "TE"):
        raise RuntimeError("CHANNEL env must be EN or TE")

    # Paths
    topics_file = cfg["topics"][channel]
    review_dir = cfg["output"]["review"][channel]
    ensure_dir(review_dir)

    # Pick topic
    topic = pick_topic(topics_file)

    # Create a unique job id
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    job_id = f"{channel}_{ts}"
    job_dir = os.path.join(review_dir, job_id)
    ensure_dir(job_dir)

    # Prompt local LLM to generate package
    system_rules = cfg["prompt_rules"][channel]
    prompt = f"""
You are a YouTube content agent.
Follow rules strictly.

RULES:
{system_rules}

TOPIC:
{topic}

Return ONLY valid JSON with these fields:
title, description, tags (array), script (voiceover), shorts_script (voiceover), thumbnail_text (array of 3)

No markdown, no extra commentary.
"""
    llm_text = ollama_generate(prompt, cfg["ollama"]["model"], cfg["ollama"]["url"])

    try:
        package = json.loads(llm_text)
    except Exception:
        # Save raw to debug
        write_text(os.path.join(job_dir, "llm_raw.txt"), llm_text)
        raise RuntimeError("LLM did not return valid JSON. Check llm_raw.txt")

    # Write scripts
    voice_text = package["script"].strip()
    voice_path = os.path.join(job_dir, "voice.txt")
    write_text(voice_path, voice_text)

    # TTS
    wav_path = os.path.join(job_dir, "voice.wav")
    piper_tts(
        cfg["piper"]["exe"],
        cfg["piper"]["voices"][channel],
        voice_path,
        wav_path
    )

    # Build video
    mp4_path = os.path.join(job_dir, "video.mp4")
    build_video_ffmpeg(wav_path, mp4_path, package["title"], channel)

    # Output metadata for n8n upload
    meta = {
        "channel": channel,
        "topic": topic,
        "title": package["title"],
        "description": package["description"],
        "tags": package["tags"],
        "thumbnail_text": package.get("thumbnail_text", []),
        "status": "READY_FOR_REVIEW",
        "approved": False,
        "videoPath": mp4_path.replace("\\", "/"),  # n8n likes forward slashes
        "jobDir": job_dir.replace("\\", "/"),
        "createdAt": ts
    }
    write_json(os.path.join(job_dir, "meta.json"), meta)

    print("DONE:", job_dir)

if __name__ == "__main__":
    main()